.PHONY: build test lint fmt check cli-only deny clean install uninstall release release-dry-run update outdated doc help

# Date-based version: YYYY.M.D (semver-compatible)
VERSION := $(shell date +%Y.%-m.%-d)
TAG := v$(VERSION)

# In-place sed differs between BSD (macOS, needs an explicit empty suffix) and
# GNU (Linux, rejects one). Detect once so `make release` works on either.
SED_INPLACE := $(shell sed --version >/dev/null 2>&1 && echo "sed -i" || echo "sed -i ''")

# Default target
all: help

# Show help
help:
	@echo "symgraph — Semantic code intelligence MCP server"
	@echo ""
	@echo "Usage: make [target]"
	@echo ""
	@echo "Development:"
	@echo "  build            Build release binary"
	@echo "  test             Run all tests"
	@echo "  lint             Run clippy lints"
	@echo "  cli-only         Lint + test the lean build (no MCP server)"
	@echo "  deny             Supply-chain check (advisories, licenses, sources)"
	@echo "  fmt              Format code"
	@echo "  fmt-check        Check formatting without modifying"
	@echo "  check            All gates: format, lint, test, lean build, supply chain"
	@echo "  doc              Generate and open documentation"
	@echo ""
	@echo "Installation:"
	@echo "  install          Build and install symgraph to /usr/local/bin"
	@echo "  uninstall        Remove from /usr/local/bin"
	@echo ""
	@echo "Release:"
	@echo "  release          Create and push a date-based release ($(TAG))"
	@echo "  release-dry-run  Preview what a release would do"
	@echo ""
	@echo "Maintenance:"
	@echo "  update           Update dependencies"
	@echo "  outdated         Show outdated dependencies"
	@echo "  clean            Remove build artifacts"
	@echo ""
	@echo "  help             Show this help"

# Build the project
build: check
	cargo build --release

# Run tests
test:
	cargo test --all-features

# Run clippy lints
lint:
	cargo clippy --all-features -- -D warnings

# Format code
fmt:
	cargo fmt --all

# Check formatting without modifying
fmt-check:
	cargo fmt --all -- --check

# Lint and test the lean feature combo: the same `symgraph` binary without the
# MCP server (no rmcp/axum/tokio), which is every command except `serve`.
# Nothing else exercises the `#[cfg(feature = "server")]` gates, so a missing
# one would only surface here. CI gates on this, so `check` has to cover it or
# a green local run can still push a tag that CI rejects.
cli-only:
	cargo clippy --bin symgraph --no-default-features --features sqlite -- -D warnings
	cargo test --no-default-features --features sqlite

# Supply-chain gate: advisories, licenses, sources, bans (see deny.toml).
deny:
	cargo deny check

# Run all checks (format, lint, test, lean build, supply chain)
check: fmt-check lint test cli-only deny

# Install to /usr/local/bin. One binary: `symgraph serve` is the MCP server.
install: build
	install -d /usr/local/bin
	install -m 755 target/release/symgraph /usr/local/bin/symgraph
	@# Builds before the binaries were merged also installed `symgraph-cli`.
	@# Remove a leftover so it cannot shadow the real binary on PATH.
	@rm -f /usr/local/bin/symgraph-cli
	@echo "Installed symgraph to /usr/local/bin/symgraph"

# Uninstall from /usr/local/bin
uninstall:
	rm -f /usr/local/bin/symgraph /usr/local/bin/symgraph-cli
	@echo "Removed /usr/local/bin/symgraph"

# Clean build artifacts
clean:
	cargo clean

# Show outdated dependencies
outdated:
	cargo outdated

# Update dependencies
update:
	cargo update

# Generate documentation
doc:
	cargo doc --no-deps --open

# Show what a release would do without making changes
release-dry-run:
	@echo "Version: $(VERSION)"
	@echo "Tag:     $(TAG)"
	@echo ""
	@echo "Files to update:"
	@echo "  Cargo.toml         (version = \"$(VERSION)\")"
	@echo "  manifest.json       (version: \"$(VERSION)\")"
	@echo "  Formula/symgraph.rb  (regenerated by the release workflow after the build)"
	@echo ""
	@echo "Git operations:"
	@echo "  git commit -am 'release $(TAG)'"
	@echo "  git tag $(TAG)"
	@echo "  git push origin main --tags"

# Create and push a release with date-based versioning
release: check
	@if [ -n "$$(git status --porcelain)" ]; then \
		echo "Error: working directory is not clean. Commit or stash changes first."; \
		exit 1; \
	fi
	@echo "Releasing $(TAG)..."
	$(SED_INPLACE) 's/^version = ".*"/version = "$(VERSION)"/' Cargo.toml
	cargo check --quiet 2>/dev/null || (echo "Cargo.toml version update failed"; exit 1)
	jq --arg v "$(VERSION)" '.version = $$v' manifest.json > manifest.json.tmp && mv manifest.json.tmp manifest.json
	git add Cargo.toml manifest.json
	git commit -m "release $(TAG)"
	git tag "$(TAG)"
	git push origin main --tags
	@echo "Released $(TAG) — GitHub Actions will build and publish artifacts."
