# Generated by scripts/release.py (release-kit) from the v2026.10.1 release — do not edit.
class Symgraph < Formula
  desc "Semantic code intelligence: symbol graph + MCP server for codebases"
  homepage "https://github.com/grahambrooks/symgraph"
  version "2026.10.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/symgraph/releases/download/v2026.10.1/symgraph-v2026.10.1-aarch64-apple-darwin.tar.gz"
      sha256 "a132a741ef6c2d8ee4cb4f5b4b4a6551362bd4a025a7786f3eef12ae2569614a"
    end
    on_intel do
      url "https://github.com/grahambrooks/symgraph/releases/download/v2026.10.1/symgraph-v2026.10.1-x86_64-apple-darwin.tar.gz"
      sha256 "4d63e933e7a85a6ec0cb44e2c8166330513218fb8ef6e514f17a90b499075343"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/symgraph/releases/download/v2026.10.1/symgraph-v2026.10.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "c80a3204f739b9a396fc59d11261be20457a7056b22127436075b4a6b49bc103"
    end
    on_intel do
      url "https://github.com/grahambrooks/symgraph/releases/download/v2026.10.1/symgraph-v2026.10.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "af4622f2a6bae17c2ac506ed2b78bc67e670f33cc0e15398338f4a33052849d9"
    end
  end

  def install
    bin.install "symgraph"
  end

  test do
    assert_path_exists bin/"symgraph"
  end
end
