# Generated by scripts/release.py (release-kit) from the v2026.9.2 release — do not edit.
class Symgraph < Formula
  desc "Semantic code intelligence: symbol graph + MCP server for codebases"
  homepage "https://github.com/grahambrooks/symgraph"
  version "2026.9.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/symgraph/releases/download/v2026.9.2/symgraph-v2026.9.2-aarch64-apple-darwin.tar.gz"
      sha256 "94c90a237b9dc8a8fd43b0177124f2814d8b88a639d6f73b82083c7ef0a491e8"
    end
    on_intel do
      url "https://github.com/grahambrooks/symgraph/releases/download/v2026.9.2/symgraph-v2026.9.2-x86_64-apple-darwin.tar.gz"
      sha256 "c92ce4b9305e5a6789ae4d478a2a2b28b1cb61c9e887feb022556345c1ef354b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/symgraph/releases/download/v2026.9.2/symgraph-v2026.9.2-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "ffd5ac971b816a2894b0bba00f6101b67cdf1984fa2680d6b4aec0756e41c200"
    end
    on_intel do
      url "https://github.com/grahambrooks/symgraph/releases/download/v2026.9.2/symgraph-v2026.9.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "4bc45c167eba80bc9e58f4eed8dff398700d5fb16f4547d7c1ccbe127801fe54"
    end
  end

  def install
    bin.install "symgraph"
  end

  test do
    assert_path_exists bin/"symgraph"
  end
end
